# Copyright 2022 Cognite AS

## Import the Libraries and Modules

In [1]:
import sys
from pathlib import Path

utils = str(Path("../utils").resolve())
if utils not in sys.path:
    sys.path.append(utils)

from cognite_auth import interactive_client

## Create the Cognite Client

In [2]:
c = interactive_client()

## List operation

**Code Pattern**
`client.<cdf_resource_type>.list()`
where **cdf_resource_type** = { data_sets, assets, time_series, events, files, labels, sequences, relationships ... }

### List the CDF Resource types

In [3]:
c.data_sets.list()

DataSetList([<cognite.client.data_classes.data_sets.DataSet at 0x1e1f1555490>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f1787710>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f1787910>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1e20d1490>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f1785350>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f1764410>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f1773cd0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f105ef90>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1e2268e10>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f178d450>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f1764d10>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f1783690>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f179b390>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f1764b10>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f17a3850>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f17a3810>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f17a3690>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f17a37d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f17a3790>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f17a3750>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f17a3710>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f17a36d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f17a38d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f17a3910>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f17a3990>])

In [4]:
c.assets.list(limit=5)

AssetList([<cognite.client.data_classes.assets.Asset at 0x1e1f1773b50>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f17811d0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f1b45dd0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1e225b250>,
           <cognite.client.data_classes.assets.Asset at 0x1e1e20e0c10>])

In [5]:
df = c.time_series.list(limit=None).to_pandas()

In [6]:
df.shape

(2089, 12)

In [7]:
c.events.list(limit=5)

EventList([<cognite.client.data_classes.events.Event at 0x1e1e2269b10>,
           <cognite.client.data_classes.events.Event at 0x1e1f2fee110>,
           <cognite.client.data_classes.events.Event at 0x1e1f32e9d50>,
           <cognite.client.data_classes.events.Event at 0x1e1f1ad7890>,
           <cognite.client.data_classes.events.Event at 0x1e1f1754610>])

In [8]:
c.files.list(limit=5)

FileMetadataList([<cognite.client.data_classes.files.FileMetadata at 0x1e1f36f4710>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f36f5050>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f36f4bd0>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f36f47d0>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f36f4790>])

Similar code for listing other resource types


```
c.labels.list()
```
```
c.sequences.list()
```
```
c.relationships.list()
```

In [9]:
c.labels.list(limit=5)

LabelDefinitionList([<cognite.client.data_classes.labels.LabelDefinition at 0x1e1e2268990>,
                     <cognite.client.data_classes.labels.LabelDefinition at 0x1e1f30de2d0>,
                     <cognite.client.data_classes.labels.LabelDefinition at 0x1e1f1b2df50>,
                     <cognite.client.data_classes.labels.LabelDefinition at 0x1e1f3274150>,
                     <cognite.client.data_classes.labels.LabelDefinition at 0x1e1f381a2d0>])

In [10]:
c.sequences.list(limit=5)

SequenceList([<cognite.client.data_classes.sequences.Sequence at 0x1e1f381b950>,
              <cognite.client.data_classes.sequences.Sequence at 0x1e1f34bc090>,
              <cognite.client.data_classes.sequences.Sequence at 0x1e1f38454d0>,
              <cognite.client.data_classes.sequences.Sequence at 0x1e1f38450d0>,
              <cognite.client.data_classes.sequences.Sequence at 0x1e1f3844750>])

In [11]:
c.relationships.list(limit=5)

RelationshipList([<cognite.client.data_classes.relationships.Relationship at 0x1e1f32e9cd0>,
                  <cognite.client.data_classes.relationships.Relationship at 0x1e1f3845cd0>,
                  <cognite.client.data_classes.relationships.Relationship at 0x1e1f3846190>,
                  <cognite.client.data_classes.relationships.Relationship at 0x1e1f3844150>,
                  <cognite.client.data_classes.relationships.Relationship at 0x1e1f3844910>])

### Filter the list results

using label filter, the data in cdf doesn't have these labels. But it is an example on how to filter with labels

In [12]:
from cognite.client.data_classes import LabelFilter

In [13]:
c.assets.list(labels=LabelFilter(contains_all=["industrial-assets"]),limit=5)

AssetList([<cognite.client.data_classes.assets.Asset at 0x1e1f1755c10>,
           <cognite.client.data_classes.assets.Asset at 0x1e1e20e8190>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3833bd0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3847e50>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38456d0>])

In [14]:
c.assets.list(labels=LabelFilter(contains_any=["industrial-assets"]))

AssetList([<cognite.client.data_classes.assets.Asset at 0x1e1f3846b10>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3845050>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3847010>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3824750>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3826d10>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3824a90>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38fc650>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38fc8d0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38fc950>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3825d50>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38fccd0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38fd150>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38fc150>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38ff050>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38fef50>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38febd0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38fe9d0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38fe8d0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38fe6d0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38fe650>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38fe550>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38fe3d0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38fe2d0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38fe1d0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38fdfd0>])

Other filters

In [15]:
c.data_sets.list()

DataSetList([<cognite.client.data_classes.data_sets.DataSet at 0x1e1f36f4fd0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f1b8b190>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f1b2e050>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f35ca450>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f35c8dd0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f38fc110>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f38fd250>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f38fc610>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f38fc0d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f38ff450>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f38fc310>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f38fd5d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f38fc810>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f38fd8d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3825390>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3824fd0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3825350>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3825010>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3825050>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3825110>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3825210>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3825090>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3824550>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3825190>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3827110>])

In [16]:
c.data_sets.list(write_protected=True)

DataSetList([<cognite.client.data_classes.data_sets.DataSet at 0x1e1f38188d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f381add0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f38189d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3819bd0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f38335d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3832ed0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3830f10>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3831690>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3831450>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f38337d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3833690>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3833d50>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f3831d90>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f390a910>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f390a8d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f390a750>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f390a890>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f390a850>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f390a810>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f390a7d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f390a790>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f390a710>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f390a9d0>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f390a990>,
             <cognite.client.data_classes.data_sets.DataSet at 0x1e1f390aa10>])

In [17]:
c.assets.list(root=True)

AssetList([<cognite.client.data_classes.assets.Asset at 0x1e1f36f4250>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f1765690>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d22d0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d0250>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d04d0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d1a90>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d0190>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d0b10>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d3390>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d0390>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d0290>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d2310>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d3290>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d3110>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d3250>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d32d0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d3190>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d3150>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d30d0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d3350>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d31d0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d3410>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d3450>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d3490>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d34d0>])

### Iterate over the list

In [18]:
for data_set in c.data_sets:
    print(data_set.id) # do something with the data_set

532492593814
3708248994472
8971087276716
22547179591127
32889565298826
39210236434027
40327729659769
48758153143218
58158657947049
58839366849857
77646949468688
85963087988610
86545673296094
88809449333750
91028975699979
99825339813632
104573554199652
106313613626018
111662049520578
140804500368758
145208858652069
146987707262722
168085293540831
179556465647798
197929698661134
198122773158762
199327379323816
206245056521975
215787008330337
216292905815470
245211532024983
248638948877491
252666839699577
257089475305167
269244871670358
270019166497168
270478968056738
280384459601303
282044034755572
300212271108879
302428767654888
304901974689240
314274225507819
319694119277473
327168443834829
332047216091763
334893065260762
342164539129005
343884367520567
351455938750371
351677402697202
353712872146981
356556244549877
360770756365631
361044291120590
361983842667871
366735187905526
367655503293353
371471186486047
371567262787826
373080082861177
374204154593058
382894356027718
383066267796045
383753923143873
385972676194758
386353505713897
390179783824555
391414095118278
404471063348808
406431760122242
413061222491199
413965148048302
415288079495233
427431636839196
429165497317995
432685068344160
433036204648308
433265370909592
434019636830057
443116462040741
446762918876037
448190392315812
449268054362853
449548606820413
462194125035131
463575659130775
465766172081624
473816852723090
475478346606191
479684261347340
479858170499604
490409063677896
490550367174858
494287051929265
496051429731132
502170041871567
513185859774038
522304100048078
528566429918169
528621123672780
533353862940890
546967672490966
549213080710281
559502720486651
564835584293954
567191607921657
575201612783267
580309958313586
596198678921811
599553620410680
604961095741056
609556684295853
619824695038924
621183638086794
621288550636820
622035521948167
622654156128468
628533913420862
631718099623657
633834219402392
639648821583111
641983919446570
643872147234439
644580965252057
646997894298288
648458141283169
648983665321516
652544550111155
655334118870390
667849636971004
692953582196731
703084601901793
708537326924316
710802418669543
713130601702471
716976346814951
723591686585852
725966825136179
727544688426623
738184721860467
746472989768288
748616310034138
754258185128677
771376250286324
781279975903043
795659557428953
798497403683373
804133470587960
804225262817351
812076573357531
817097687377880
817114135115991
821729274408808
823161786853523
826761420013544
830381672316401
831254441409725
838086826086989
840629724410194
842419528435765
848276701963218
853154154335514
862664667214331
868380830013266
874868730032339
888027364703447
889452778498716
890152991890022
906242300278302
911216358192603
918592566336184
920221886368799
922201656914718
941938870420442
945879140892084
950745464373043
952090479554162
954928425324575
960250379695725
961946951876136
962357111547552
968707581577342
974658736134817
988086870624681
999303290864023
1006272666556849
1033956203226101
1055890999245178
1059268772539258
1062225714431722
1069078470081562
1069108139629359
1069554777427556
1077532010327178
1085289270190123
1107177383117395
1130451088557745
1139000062711017
1141373574368248
1150408489563842
1158191685524419
1158245760718226
1163723778772280
1170131357124402
1177098242095797
1179901601543761
1182254724540116
1185379204284366
1201724655593148
1202614998030699
1204659439623409
1205762913409378
1207419306061403
1214649783362589
1216258026128952
1221857277384525
1225524975600227
1229896871721511
1241330167565866
1250270226890324
1251272489873371
1257443571509816
1257704953866882
1261168789199063
1275915436327503
1280765655926353
1282062143478093
1282458501305523
1288446642529445
1292072704503015
1306101474874408
1310301878819043
1311557794448791
1316852108822915
1322039641564162
1325550905109754
1334403970201787
1335974605383758
1339167715961126
1343517314257611
1345141187162439
1348843871235415
1366801261827676
1371996313381598
1377618256482266
1379285418425613
1395837932266356
1399248851345249
1405078456049484
1407152301190633
1408826934075429
1410441463659350
1410817623288435
1416144622016281
1417504489694440
1437069057888090
1444875267593700
1460997700539257
1473681769768562
1476863929372273
1479695427068553
1479859102324048
1481223137220244
1494962522520179
1497348963839079
1498932839973608
1502893976524035
1507415726010715
1508853694935928
1516463030274855
1518216444980401
1523787130682392
1524680983700698
1526456776531167
1532027212687982
1543513110408351
1543671114961434
1547476927628082
1551836458301371
1552051149042891
1561563571153069
1587961605158576
1588429512031562
1592832778753807
1592917301408796
1593428488435041
1599807693367908
1604114553000868
1605844253137626
1614986846616846
1620689599109719
1621973293707004
1631760662759693
1641607801569174
1653105143684388
1655831984591737
1656307260690554
1674049361118152
1682081983385086
1693929257222548
1698338843871346
1701895473801216
1702154281334276
1706434942098141
1707976748808707
1712580253673439
1717506819349544
1720743512081697
1720753366928347
1732294606267560
1732727878938189
1737457001048699
1738519957792732
1740780225682649
1747856776032809
1748345613069565
1750274230457497
1751446784428404
1752864791548892
1753859835900799
1781014955065063
1789173885320064
1790253453828748
1794370249726288
1803290549349038
1809543230872644
1813555308922183
1817292694398048
1819612230300151
1828067098665441
1828703952665519
1833453309074835
1843379459643733
1857079057906957
1863770681242809
1864623766192844
1864635290563035
1884540635691659
1886546571747999
1895449624133541
1900770456801810
1907752641369576
1908741361361709
1910970948827912
1913038613496780
1929610961715132
1934685661543316
1942362572002902
1946995391869517
1952587161485482
1954747345924765
1959968568110613
1963068089734413
1967975012488138
1979885435250559
1989032900602918
1990351901786303
1999140268933734
2000381036676167
2001779596692798
2003426439066220
2004275097557060
2006874460682820
2007475723851843
2010926689828620
2011779359651204
2013322688485496
2022625971638744
2032957843429776
2036480507542760
2041823343172129
2048449721536080
2049448152475997
2053631970639347
2055148352894156
2055427241683204
2070377851473516
2076049946223270
2076371233174065
2080214821397583
2081033156072552
2084872831251333
2086618822392102
2087013198427290
2087707021674810
2087890923208881
2100806649564178
2100865133097895
2105816208354166
2107133669343331
2112085192609282
2120275915768684
2121229839567051
2130912180259306
2136524331258196
2145427014541445
2146641098675213
2154946647964581
2155653646196720
2157837334446681
2158198703770447
2158417735537758
2165836082097760
2165969613254318
2166061438529203
2168263397591759
2170294417906859
2175152792732886
2183554967062468
2190765946098446
2199269918525463
2202053283896355
2211896621442173
2216345027946073
2228561134884327
2234916403658822
2238694842784134
2242860718287646
2247282766885987
2251923110868351
2270685781082179
2274224619096450
2278720343066350
2278860425327819
2283038941199500
2288702427156613
2294035991131906
2297036148906945
2298783446247822
2302574189838796
2304188028315611
2312404640641680
2321470076939145
2328424159296909
2328874100370204
2329898891769772
2342711677808663
2348496359891873
2362826850895131
2367684652022147
2372322479882281
2387444884144279
2388878271722297
2400267457774931
2405246425701403
2407169140096262
2416264946706357
2419060250033884
2431053139606395
2437010206622903
2455963958369937
2461063811878702
2468542287064164
2471274175128842
2477315746812839
2479632565248609
2490833447988795
2503748567311116
2504349779542087
2506556781328576
2508161350337467
2511410068159976
2515479368700393
2523195970186524
2528428316884654
2528911606274376
2530792656534022
2539547555786952
2542748006079220
2549777223194629
2553579104506664
2562291634391494
2566206333470905
2566919603643804
2569399397330280
2570325016218389
2584735913388066
2585807599522491
2603356844421037
2606186489548451
2643068784551291
2648803228150271
2660967612150257
2669928268835509
2677769742989193
2681135282752042
2681998300430763
2683840985568138
2684762043942063
2686406063087083
2690506626357359
2697380900418431
2697647321085456
2701219236708955
2707004872677087
2712527563164807
2714360670642521
2715648553624699
2723280590887824
2730151622033299
2736472442884836
2739378655952392
2745766591440228
2748583307904895
2750367382323356
2755684955624724
2758270384847173
2761019829124598
2762911056966549
2764923743457275
2767068002060556
2772693738155375
2773404321714470
2779298869985864
2782365176345025
2791022208205594
2802892716241974
2808682157342157
2814075393904743
2814308704490141
2823096012388271
2829041337204995
2829255563463317
2829507119800183
2830841203522276
2832194960304291
2835391039399971
2843080094497016
2844420040823851
2863083222824019
2864028039322318
2864084667188549
2865315723998713
2866588920299148
2878151803791487
2883022880948923
2888899222977130
2894001993986892
2909088323190810
2910359974429237
2910874487472253
2911256178469946
2911661927586981
2920878072079918
2921423200866915
2922185029699191
2926170034395795
2943365034383957
2947927670268479
2959128939610251
2960291722519684
2961132027173142
2965083518868723
2967131971888708
2971522514911109
2971637976007819
2981188893992453
2981567217401545
2987360961444415
3019323552983707
3026346476590298
3041437975324122
3045568420517075
3050343233034734
3063556664814733
3071051556540113
3073360283621350
3080098747541952
3090175246942918
3097799896300265
3099547207394818
3109354098195961
3114562492264894
3120945599259676
3123288396438708
3128575396904089
3128701522386857
3131899688655091
3140729701001983
3144031455705029
3150157819272614
3164107093335332
3169594204643666
3170354942225016
3171366310320678
3179270895544398
3180131923927704
3193076875681489
3221694486809650
3224972408618222
3227705308010108
3230714509134473
3231699189902647
3234183566463212
3244712267049468
3252863470388905
3261236690954880
3262481510309580
3265443361732514
3266147401380228
3280574413693342
3287820411765745
3297194535279959
3298380217362572
3298935352970736
3299453579048689
3301955055471451
3302304397764914
3317891590714558
3333812893008964
3335318105159292
3338733773633920
3355731989695589
3367713126145156
3368330750859886
3378767309410957
3381409674111087
3382913029471631
3388221673305633
3389301527726743
3391104403306813
3393601245516851
3397248522627607
3402534891148056
3404629494770529
3428499361999735
3436864625169384
3444323436250800
3454682137601544
3457368556271423
3462143781298735
3462310269585919
3486064982377811
3500061215272723
3507031004300529
3510788110014927
3511163603305418
3515245018468204
3529110873538820
3529302691607226
3537344943069726
3543743391411107
3543993073242866
3554263512677325
3556565438145060
3563377918065274
3565213266965394
3565337827844169
3578964755308630
3579934415299374
3589217527491953
3594072405435655
3605750943514445
3608455444535346
3608615516230687
3610024291650900
3610074902696354
3625288193520803
3641331840264683
3641617916302981
3651001084031369
3655333560465258
3662542168526863
3664424586466493
3669200684280916
3682427831848495
3685752564837946
3696121708027350
3697778639944040
3703710687922399
3710718861230855
3711240786717478
3713911304657310
3721182921446592
3722751284432185
3733968516019731
3740096947506843
3740111082469728
3745648415825307
3749122422937367
3750840315198849
3751120141375545
3751875097267449
3759263795744920
3765682391452196
3765902310798570
3773978879153155
3783746997545497
3794563852459650
3800498821188785
3800911452820180
3805704781905558
3815242376959400
3815514760449738
3824614335734696
3828153965543112
3830681777151080
3831706406390209
3832321040888193
3835314484833739
3836955444662784
3848124341002420
3860783980896816
3862381826615487
3864955317242534
3869527237329571
3872344724289623
3877646162208394
3878639911984981
3886318856603660
3917702687898205
3920244778883779
3924304056401318
3928463193601741
3939502344192846
3943751568013551
3950596727332636
3950678655551597
3954959707788761
3960208359913788
3960584930107313
3976107012307108
3982295575048428
3988379457964629
3989178566058017
3989459344158182
4004935783161542
4010941073966255
4014420929451670
4037933017324208
4042944056718239
4057294432221931
4059991665993701
4064611348909151
4069217386658534
4085313629438009
4089554646832446
4108718241711122
4108826492904666
4109764059855187
4118084374390093
4118219044676205
4120250262454082
4123272018176181
4126713562813832
4130057822569445
4135729107043139
4139182864858070
4158819849330865
4166959852225399
4167273839244078
4171987262740887
4184380438509218
4185426435703370
4186039898432735
4192476152221513
4197781512705091
4198465485109543
4203065344689810
4203967703520451
4207122715549721
4209824204794440
4214936602614572
4219295039266605
4229268820820420
4233571227781494
4246909034825718
4248533333143857
4250004790588935
4250864005588055
4266287005388355
4270422284255266
4280910206734727
4282715273465147
4286787021265040
4286836962388919
4304481465774348
4310732894240737
4313767068448871
4318194516088622
4319480107942438
4320139463675511
4325074729413480
4327586284635840
4331071906211675
4338250878599695
4339754203585974
4340348255324159
4340995703376020
4342099530489135
4349182572455794
4353792050693837
4360915987386966
4364000403696354
4367080077305747
4369337212099050
4371798722812486
4374962094927501
4376664350048143
4376854949258633
4379626006943766
4397486057907956
4398088023276752
4401961752868171
4406628759478623
4419744397114747
4426597301787073
4430077514128268
4445044907858927
4446987946101068
4452771281937029
4454816505788968
4470810975598267
4483543895251647
4487345076882078
4488760112881998
4491172761130378
4501800679948022
4504778628916329
4509864682906136
4513882317847647
4528258346218505
4538194045642268
4547202495335366
4548766474877473
4553081742337058
4572068358447360
4591173305634855
4593586803377589
4595063913261877
4595297790087416
4597789186646518
4603840493329850
4611220583149009
4627496525082831
4642872519072728
4645676333505922
4647750613843999
4661170722714223
4665561133504372
4669171747598098
4671332310722310
4675066210396067
4690355550141963
4690597642546034
4696192033674777
4699332597187541
4704096779615697
4714796198904843
4724625952069311
4727137113280906
4737404532764922
4741675779990177
4750475368646754
4759762088234475
4760582323278914
4763349408701212
4765936836627268
4771909120640346
4772743229479018
4778335149992118
4785613012257898
4786843536962743
4797055033234981
4813252204819428
4818674727361059
4830923224268568
4868425160444663
4872105183521852
4877607458482313
4880510395456016
4881247139382421
4888182179958172
4892485490064587
4892567865239309
4894458703988600
4900115247853907
4909924966067271
4917364837390161
4922142235116534
4934730363850008
4937224345337425
4947966000288761
4949366175023809
4956521392955480
4961768681850343
4962368703848604
4981825946636022
4990976646580978
4993199363277375
4993826289703318
4998324788751617
5003711736056488
5007714911429796
5015735732670106
5022996324331693
5031504297889108
5035147674881783
5060425428066370
5061751666006529
5062667771492321
5069039178469756
5073053999289431
5073427721579068
5074898263518120
5077375456757587
5082253918766013
5087716596235727
5089406646659058
5099410328505451
5100295442148670
5102695953153885
5117260373530223
5121272530900136
5131265672206354
5132738962116218
5133386670464257
5146577882544528
5147851305914422
5148678540681478
5149127651428743
5157914652010988
5166342102735323
5187812703816576
5190809828030530
5194975779110410
5202274727016936
5203302430860998
5223664459435863
5223804946481743
5225642168473062
5228544399327259
5230951127573373
5231613490222168
5242862246344656
5244363859318158
5246382615792699
5248741486654466
5249253246192955
5255428414067332
5255790324291798
5255891984226600
5259680577914072
5259904641896313
5264544923268492
5265699056369031
5286550981105628
5291863921574870
5307107152212504
5307928074976960
5308923459005818
5310338725863317
5313330929151202
5322464025444402
5336927592491898
5337080995126847
5348862471123167
5351702796918287
5351902645994070
5352739843862708
5355737712050282
5385223476765501
5389491003311475
5389523103028547
5416737360773608
5421950597697552
5429923877930268
5431660820535464
5443564935873282
5444580799564484
5453544129144699
5458861699381514
5462958601995789
5466188251932699
5469298824003198
5473759795287288
5480994399212609
5482608841022141
5492159518015725
5496281761341764
5503119165422481
5504351442715079
5504718422852292
5529946859103236
5537958370636314
5538701411987514
5540481487135501
5543860453418313
5545204558702440
5548572851312583
5550719070476390
5552099697156104
5563247542002918
5571789513418702
5591078598889629
5593417748222709
5593526574314854
5599377941511199
5603269810976174
5608856813921158
5609811992526231
5610387767824550
5610445506143666
5612298591179985
5618376613737212
5634669407148784
5636700358483754
5637075363549394
5644560775559356
5650396680422506
5656838368809032
5670414628875195
5680074084630063
5697390865023064
5722419564427499
5723202641529564
5726637225271203
5745164085629001
5746443928276047
5750789016011035
5758555445103906
5760681210931035
5764181768390632
5772791385245711
5783002336749928
5783466020054643
5791270937686567
5791503208384010
5793368425348217
5798841174146415
5802558653306497
5804009841005107
5806821925646140
5807157266867063
5818933780575676
5820068845725197
5824872557067312
5837793538761547
5843482480872869
5843649462615042
5853318511631602
5867680815362245
5873472840202959
5876907661800100
5883811906445078
5889131149771712
5892252437044557
5895092260362267
5895828894037348
5905092841876071
5915185601049719
5917917771429796
5919226178868550
5928591683990175
5930500866730453
5932833549170342
5936034085499518
5936553853716099
5937404962115219
5950689265270348
5952334902376815
5953060056519899
5955308526559132
5961396291341221
5964931741651997
5968516251684758
5974249572355587
5975380568752319
5976852927010153
5977725677462370
5987665072355316
5994829718820323
6007042579238660
6010749084902640
6024764961135244
6045439430214110
6058032377554601
6061773193277777
6072660243794946
6079466926265920
6080909909508366
6092950485275624
6097699950845901
6099467114847970
6101325858926263
6103355253065997
6104584074478418
6107826800735839
6110438101771026
6119464306081210
6125808620458155
6132921472956639
6133408726791096
6135851423850814
6148652464548393
6160835288440397
6165734471703303
6174647249533378
6186796484470238
6198497520958060
6207716302014326
6210860356737318
6219925696471411
6220011291980428
6224689001068527
6228728863319786
6231440944047471
6233562807750326
6243328012626314
6244508445665349
6249493737845072
6263768954456669
6271171207202629
6278161897846100
6282822832728891
6288958976452280
6294026477184758
6302454151776804
6303737011844403
6309911480577677
6315359988623121
6316855244604248
6323980738028238
6335023429692316
6350166411831398
6352680982275014
6367373287480150
6375115259246293
6375470044250410
6378025078839961
6393971027032637
6398971926528878
6401912660139540
6406770788802491
6407111837541454
6407427778697928
6407702796684091
6415148031186024
6438614615491818
6440133861420169
6440332305607399
6444279267085539
6444624918054706
6445051376294132
6459234200968889
6469927314515041
6488803415636535
6491411027257244
6499767951170587
6500631207581608
6507195763234610
6516972431015041
6526165464157324
6527169888206906
6548341323566252
6565779477315161
6581201040841081
6583449154416432
6586308995227750
6588644176566640
6591003247710756
6606379362970080
6608660287255177
6610801314602855
6620032840087693
6624680301620060
6639868622867939
6640929576648975
6645096120573795
6645944890075708
6659492046422624
6670840516356977
6677100133675600
6677749104518595
6688076757706453
6691749977537325
6694615199404761
6713564708028432
6716895186507859
6720070289884265
6720460100635011
6742252423376321
6745114508396110
6758642766050135
6762310414027981
6764378121661101
6772182261561641

When List is too big, then use the **chunk_size** parameter to get the list in chunks

In [25]:
for data_set_list in c.data_sets(chunk_size=5):
    print([x.name for x in data_set_list]) # do something with the list

['TestDataset_pawara', 'pawel_world_info', 'my_example_dataset', 'aleksander_my_example_dataset', 'Crístian2_world_info']
['world_info_jack', 'world_info_jack_11', 'world_info_jack', 'world_info_Timi', '1st level']
['my example', 'world_info_mohsen', 'world_info_bhaskar', 'kiyoshi_world_info', 'world_info_jack_SAYAN']
['patrick1998_world_info', 'test', 'Prince_example_dataset', '1st level K', 'SofieHaug_example_dataset']
['jonathan_world_info', 'Srujana_world_info', 'my_example_dataset_wu', 'ole_wammer_world_info2', 'smrsgv_info_jack']
['my_example_dataset_rodrigo', 'Test', 'my_example_dataset_temp', 'third example', 'hanan_world_info']
['Could anyone help remove this?', 'GPaulo2000-IFSDB', '1stLevel', 'a_my_name_example_dataset', 'gcbiotec_world_info']
['patrick1998_world_info', 'world_info_test_2', 'TestDataset', 'world_info_jack_sohaib', 'mp_two_dataset']
['Test set', 'raj_world_info', 'ruben1984_example_dataset', 'write-protected-data', 'my_dataset']
['krishna2001-Aveva.Net', 'vetle_world_test', 'world_info_shiva', 'world_info_beni', 'Alex_world_info']
['my example', 'Shiva', 'TestNK', 'world_info_jack', 'Andreea_world_info']
['world_info_jack_novajj', 'world_info_andrew', 'Rafli_world_info', 'irma_test', 'world_info_wei2010']
['1st level-gs', 'my_example_dataset', 'heydar_worl_info', 'my_example_dataset_www', 'Gayathri_world_info']
['dil_world_info', 'Maciukas_example_dataset', 'Andreea_world_info', 'Shiva', 'test_dataset8']
['my_example_dataset_vgr', 'world_info_areisdorf2', 'Maciej_world_info', 'second example', 'world_info_jack_as']
['world_info_sofie', 'gann2023-AvevaNet', 'Dzmitry1994_world_info', 'Vijaya_dataset', 'Tiago_world_info']
['camilla1996_world_info', 'Arpita2020-AvevaNet', 'PM_world_info', 'my_example_dataset23', 'world_info_krutip']
['mylittlepony_world_info', 'mylittlepony_world_info', 'Jorgen_world_info', 'third example', 'world_info_chandc']
['my_example_dataset_006', 'hola', 'lsun_world_info', 'myworld_info_jack', 'DipeshYogi1994_world_info']
['faraz_alm', 'Rui77', 'Nick0000-IFSDB', 'second example', 'world_info_jackcity']
['my_example_dataset', 'my_example_dataset_1', 'world_info_andrew', 'amitoj_world_info', 'rsk_ds1']
['world_info_jack', 'world_info_jack_njj', 'bojja_world_info', 'faisal_dataset', 'FirstnameBirthyear-AvevaNet']
['mfc', 'my_example_dataset_Him', 'Dag1985_2_example_dataset', 'world_info_andrew', 'world_info_jack_Manv']
['rawan_world_info', 'Adriano2024_data_set', 'world_info_jack_99999999', 'world_data123', 'Rafli_world_info']
['christian_world_info', 'world_info_john', 'SIOD1980-AvevaNet', 'neil_example_dataset', 'Mudassir_world_info']
['gcbiotec_world_info1902A', 'mylittlepony_world_info', 'my_example_dataset_001', 'mohammed_al_safwan_example_dataset', 'world_info_adeeb']
['my_example_dataset_test1', 'world_info_mugless', 'Mat1989_dataset', 'TatVF_world_info', 'my_example_dataset']
['third example', 'test_world_info', 'faisal_dataset', 'Rajat1985-IFSDB', 'JorgenAa_world_info']
['my_example_dataset', 'lucas2000-ds', 'FirstnameBirthyear-AvevaNet', 'world_info_jack_mm', 'dalvania_world_info']
['chand_world_info', 'wu_world_info', 'world_data', 'Mudassir_world_info', 'neil_v_world_info2']
['world_info_timo', 'teodor_world_info', '2nd level', 'Ruslan_world_info', 'world_info_Kush']
['emmab_world_info', 'world_info_academy2', 'pawel-test-dataset', 'second example', 'hmnasri-CDF3']
['world_info_andrew', 'smart-home-dataset', 'world_info_jack', 'angelica_world_info', 'camilla1996_world_info']
['Crístian_world_info', 'kimsb_world_info', 'JorgenAa_world_info', 'Mohamed_example_dataset', 'caroline_f_world_info']
['my_example_datasetcas', 'vinicius_peres_world_info', 'world_info_kailash', 'second example', 'Mikalay1991:my_example_dataset']
['heman_dataset', 'world_info_wwu_H2', 'frendi_world_info', 'Diana_world_info', 'world_info_1991_2']
['clement_world_info', 'john_world_info', 'sharizan1981_dataset2', 'my_example_dataset_Long', 'my_example_dataset']
['world_info_kruti', 'gayathri_world_info', 'Saurabh_world_info', 'wael__world_info', 'christian_world_info']
['LNDR_world_info', 'world_info_jack', 'world_info_jack', 'Itika_Dataset', 'teodor_world_info']
['my_example_dataset-test', 'Arya_example_dataset', 'Alq1997-AvevaNet', 'Hariharan_world_info', 'Dipesh1994_world_info']
['world_info_jack', 'world_info_juju', 'Srujana_world_info', 'EmiliesDS_v3', 'world_info_nick']
['Ravi_World_info3', 'Mohamed1996', 'Jorgen_world_info', 'world_info_wwu', 'SampleDataset23']
['Maksym1981-1-dataset', 'my_example_dataset11', 'Ajit1992-IFSDB', 'amel_world_info_jack', 'Emilie_world_info']
['test_equip', 'elize_world_info', 'Timi_dataset1', 'my_example_dataset', 'world_info_jack']
['John7638', 'TestDataset_pawra', 'grobb_ho_dataset', 'first level', 'kiyoshi_world_info']
['JH 1st level', 'aarifov_world_info', 'world_info_mi', 'subodh_world_info', 'Shaurya_DataSet']
['Ahmad1997-ds', 'andrew_world_info', 'afrendi_world_info', 'DP_TestDataSet2', 'NKTest123']
['akhilppujyamdataset', 'mylittlepony_world_info', '111st level', 'wu_world_info', 'third example']
['Muddassirmm1', 'world_info_jack', 'christian_world_info', 'ruben_world_info', 'world_info_jack']
['lala_level', 'my_example_dataset_abu', 'jd1980-AvevaNet', 'my_example_dataset', 'world_info_Sofie']
['disha_world_info_jack', 'Amin1987-ds', 'world_info_jack', 'clement_world_info', 'my_example_datasetmm']
['yahya_world_info', 'third example', 'Mudassir_world_info', 'test1', 'world_info_jack_1337']
['Srujana_world_info', 'world_info_jack_1964', 'JohnS1984_world_info', '2nd level', 'daniel_world_info']
['csv', 'yeshwanth_example_data', 'world_info_jack', 'world_info_jack_t', 'world_info_jack_ass']
['Arpita2021-IFSDB', 'pavko_example_dataset', 'christian_world_info', '3st level', 'world_info_mi2']
['mikita_world_info_jack', 'NKTest', 'vgr_world_info', 'Mallesh1993-AvevaNet', 'world_info_test_222']
['Jorgen1990_example_dataset', 'world_info', 'world_info_jack', 'emma_world_info', 'pavan1978-AvevaNet']
['Mudassir_world_info', 'name', 'Ravi_World_info3', '11st level', 'testds']
['my_example_dataset', 'my_example_dataset2', 'Shaurya_999', 'Saurabh_world_info', 'my_example_dataset2']
['grrr109 test data set name', 'shawn_ts', 'world_info_abhinav', 'world_info_jack', 'PM_world_info']
['Arya_World_Info', 'GCH_world_info', 'my_example_11_dataset', 'world_info_jack', 'world_info_jack']
['Abiinfojack', 'ahmad_world_info', 'wael__world_info2', 'tfrendi_world_info', 'my example']
['FirstnameBirthyear-IFSDB', 'third example', 'world_info_amitoj', 'kailash193-Avevanet', 'world_info_jack_121']
['srujana_world_info', 'world_info_maksym1981_1', 'irma_test', 'world_info_douglas', 'world_info_jack']
['john_example_dataset', 'world_info_abhinav', 'srujana_world_info', 'my_example_dataset', 'Yining1974-IFSDB']
['world_info_jack', 'EH_world_info3', 'world_info_jack', 'ruben_world_info', 'Jason1990_world_info']
['mylittlepony_example_dataset', 'world_info_halit', 'Hasan_Hindi_example_dataset', 'Srmk_world_info', 'world_info_jack3']
['mylittlepony_world_info', 'my_example_dataset', 'my_example_dataset_x', 'heydar_worl_info', 'dpg_world_info']
['world_info_jack', '1st level', 'ariel_world_info', 'my_abhi_dataset', 'Aman1997-AvevaNet']
['rdb_example_dataset', 'my_test_dataset', 'my_example_dataset', 'world_info', 'ruben_world_info']
['HydP2023', 'world_info_giovanna', '2nd level', 'my_example_dataset_par', 'camilla_example_dataset']
['Yahya1991-AvevaNet', 'world_info_marissa', 'E_example_dataset', 'christian_world_info', 'cc_my_example_dataset']
['world_info_academy', 'my_example_datasetca', '1st level_m', 'world_info_jack', 'breno_word_info']
['rdb_world_info', 'EH Dataset', 'sebastian1999_world_info', 'Muhammed_Muddaththir_world_info', 'dawei_world_info_jack']
['world_info_tb11', 'name', 'world_info_jack', 'world_info_jack_hv', 'Maciej_world_info']
['jayme_world_info', 'world_info_jack', 'christian_world_info', 'world_info_mfc', 'Shiva']
['irma_test', 'srmk', 'my_veryown_dataset', 'ariel_world_info', 'world_info_jack2']
['montadahar:my_example_dataset', 'mylittlepony_world_info', 'delete_me', 'ds1', 'meher']
['johnzhu-ds', 'first level', 'my_test_ds', 'world_info_jack_daniel', 'world_info_sid']
['jujus_dataset', 'mfc_world_info', 'christian_world_info', '1st level_m', 'gabor_world_info']
['henderson_world_infov2', 'world_info_jack2', 'Ricardo_example_dataset', 'world_info_jj', 'anj_example_dataset']
['tom_world_info', 'nick_world_info', 'my example', 'my_example_dataset', 'rena1990_world_info_jack']
['legit_dataset', 'mauricio2_example_dataset', 'world_info_jack', 'PM_world_info', 'kliang-test-ds']
['Krystal1986-AvevaNet', 'muygurworld_info', 'world_info', 'ds_2', 'Mark303-AvevaNet']
['3rd_level', 'Jaiprakash1988-AvevaNet.', 'second example', 'PM_world_info', 'SumitB1998-IFSDB']
['LNDR_world_info_2', 'jonH_world_info', 'mojtaba_world_info', 'talal_world_info', 'name']
['jeeva_world_info', 'Mikalay1991:world_info', 'my_example_dataset_PM', 'ali_htx', 'JFH_world_info']
['FirstnameBirthyear-AvevaNet', 'world_info_GCH', 'JP my_example_dataset', 'Magnus1994-DS', 'Abdulmonim_World_info']
['prueba_example_dataset', 'VFMProject_ClientCompany_Roger', 'Own_Create_dataset', 'phils_world_info', 'DZ_world_info']
['magnus_world_data', 'AM-Test', 'md_faraz', 'subham_world_info', 'irma_test']
['world_info_jack_MS', 'world_info_jack_name', 'world_info_jack', 'Adriano2024_101_world_info_level1', 'Raluca_world_info']
['world_info_jack', 'world_info_afi', 'world_info_jack', 'world_info_tim', 'world_info_diego']
['world_info_GCH', 'Simon_world_info', 'vetle_example_dataset', 'PM_world_info', 'world_info_afrendi']
['test_dataset2', 'Compressor1992-AvevaNet', 'viniaperes_world_info', 'world_info_mark304', 'world_info_1991_3']
['irma_test', 'world_info_andreea1', 'world_info_ole2', 'Jorgen_world_info', 'Him2_dataset']
['Hasan Hindi World Info', 'world_info_jack_new', 'my_example_dataset', '14_world_info_jack', 'jz_world_info']
['world_info_jack2222', 'jeeva_world_info', 'MRosado_world_info', 'FirstnameBirthyear-AvevaNet', 'my_example_dataset']
['anik_example_dataset', 'dzmitry1991_world_info', 'test', 'gcbiotec_world_info2002B', 'kiyoshi_world_info']
['Mudassir_world_info', 'andreas_world_info', '2nd level', 'Abu_world_info', 'second example']
['aman1997-IFSDB', 'ariel_world_info', 'my_example_dataset', 'mauricio-world-info-test-exercise2', 'E_world_info']
['Sumedh_Dataset', 'Ruslan_world_info', 'my_example_datasetq', 'Mikita1994-dataset', 'test_dataset1']
['NKTest123', 'Christian_world_info', 'grigorii_world_info', 'Function pipeline configuration', 'my_example_data_set']
['world_info_jack-1', 'Mohamed1996', 'JP_world_info', 'world_info_jack', 'Jonas_example_dataset']
['yesh4507', 'Saketh1991_data_set', 'NKTest1234', 'xiao_example_dataset', 'world_info_jack_5']
['EH_world_info2', 'Pablo1971-AvevaNet', 'ahmed_dataset', 'world_info_jack', 'world_info_kkk']
['world_info_jack', 'FirstnameBirthyear-AvevaNet', 'Aranya_world_info', 'world_info_academy', 'first level']
['meghna_world_info', 'third example', 'world_info_douglas', 'world_info_xyz', 'world_info']
['Yashwanth_data', 'GCH_world_info', 'world_info_jack', 'TestDataset', 'Ravi_World_info']
['EmiliesDS_v2', 'aarne_world_info', 'Simon_example_dataset', 'Tat_world_info', 'my_example_dataset']
['michael_world_info', 'world_info_mfc3', 'world_info_jack2_new', 'world_info_jack', 'first level']
['krny_world_info_jack2', 'world_info_jack', 'my_example_dataset', 'world_info_jack', 'NehaSingh_example_dataset']
['marissa_data_set', 'AndreasNordby_world_info', '1st lvl', 'christian_world_info', 'Aditya1999-AvevaNet']
['Fred1_example_dataset', 'HA2023', 'World info', '1st level', 'Yahya1991-IFSDB']
['DipeshYogi_example_dataset', 'Aidar_world_info', 'world_info_jack7059', 'irma_test', 'world_info_mm2']
['Diana_test', 'Gaurav Rajurkar_world_info', 'christian_world_info', 'LNDR-Data-Set', 'world_info_camilla']
['my_example_datasettestzp', 'yougiyou2000-AvevaNet', 'agnes_world_info', 'Aidar_world_info', 'Aranya5_world_info']
['lucas-2000-world_info', 'world_info_Thilak', 'mads_world_info', 'magnus_world_info', 'world_info_jack']
['T_dataset', 'third example', 'world_info_amel', 'world_info_jack', 'third example']
['world_info_jack_555', 'Simon_world_info', 'world_info_jack_sid01', 'world_info_jackG', 'cp_wells']
['world_info_maksym1981_3', 'world_info_Root_Assert_Error_Test_011', 'kliang_world_info', 'Patrick1998-AvevaNet', 'test_sensor_1']
['dataSet1demo', 'Aranya2_world_info', 'grigorii_world_info2', 'YuiNish', 'world_info_jack']
['jz_world_info', 'amelfrendi_world_info', 'world_info_jack_005', 'delete_me', '1st level']
['Andreea09', 'Crístian1_world_info', 'my_example_dataset', 'yen_example_dataset', None]
['world_info_jack2', 'mduque_world_info', 'toye_world_info', 'world_info_jack', 'ds_3']
['greynoso71_world_info', 'dpg2_world_info', '2nd level', 'world_info', 'EH_world_info4']
['johannes_world_info', 'Rafli_world_info', 'daniel_world_info', 'world_info_Vipul', '3th level-gs']
['xiaoniuzhang_world_info', 'patrick1998_world_info', 'pavko_world_info', 'world_info_doug', 'world_info_Root_Assert_Error_Test']
['world_info_jack_1990_aida', 'Sai1988-AvevaNet', '2nd level', 'Cognite', 'Elize_example_dataset']
['tsk_my_example_dataset', 'faisal_world_info', 'pligarcia_example_dataset', 'vetle_world_info', 'Kushagra_1_world_info']
['Mudassir_world_info', 'Dag1985_example_dataset', 'GCH_world_info', 'Rostyslav1984-IFSDB', 'JP 1st level']
['003Khobar_world', 'Alex1995_world_info', 'world_info_jack_23', 'Hariharan_world_info', 'dasor_world_info']
['gabor_world_info', 'world_info_sky', 'world_info_moe7', 'jd1980-IFSDB', 'henderson_world_info']
['second example', 'second example', 'Mikalay1991:world_info', 'Maciej_world_info', 'heydar_worl_info']
['4th level', 'my_example_dataset_dw', 'Dzmitry_world_info', 'evg-1980_dataset', 'my_example_dataset']
['rsk_dataset', 'world_info_shehan', 'world_info_muglessdurry', 'world_info_jack23', 'world_info_jack']
['Jorgen_world_info', 'world_info_daniel1991', 'Hachem_example1', 'world_info_jack_sohaib1', 'my_example_dataset_PJM']
['world_info_jack', 'Balcos_world_info', 'irma_test', 'Miles_example_dataset', 'world_info_maksym1981']
['RI_world_info', 'my_example_dataset', 'Task_126_ds_python', 'Ruslan_world_info', 'wu2010_world_info']
['world_info_moe6', 'lucas-2000-ds', 'Mohammed1995', 'krishna2001-IFSDB', 'my-custom-dataset']
['my_example_dataset', 'cristian', 'EH_world_info5', 'LC_1st level', 'Gaurav Rajurkar_world_info']
['srmk', 'Sample_Veda', '1st level', 'my_cool_example_dataset', 'Ravi_dataset2']
['world_info_jack', 'world_info_jack_Manvendra', 'Vani_99-ds', 'irma_test', 'yeshwanth_45']
['Vani_1999', 'irma_test', 'Harsha2000-IFSDB', 'sofie_dataset', 'ola_world_info']
['my_example_dataset', 'nick_world_info', 'world_info_chirag', 'my_example_dataset_nikhil', 'chand_world_info2']
['world22_info_jack', 'andreea', 'lsun_example_dataset', 'world_info_vero', 'faraz_alam']
['my example', '2nd level', 'Aldo_world_info', 'dpg_example_dataset', None]
['second example', 'ariel_world_info', 'VFMP_Sf05ynhm0v', 'world_info_jayanth', 'Maria_world_info']
['DP_TestDataSet', '2nd level_m', 'vetle_world_info', 'Jorgen_world_info', '5th level']
['mauricio-world-info-test-exercise', 'ariel_world_info', 'world_info_ruben1984', 'world_info_jack_kk', 'David19652_world_info']
['world_info_camilla', 'HA2023', 'christian_world_info', 'shubham8_example_dataset', 'Alfredo2_world_info']
['AP_example_dataset', 'world_info_jack', 'mohsen_example_dataset', 'olav_world_info', 'Ravi_World_info2']
['Tatsiana1994test', 'world_info_gcbiotec', 'pratish_integrate_dataset', 'test_dataset4', 'my_example_dataset_wu_2']
['Jose_example_dataset', 'xxxxx_DP_TestDS', 'TestDataset', 'maude_world_info', 'Harsha2000-AvevaNet']
['jz_world_info', 'world_info_jack_003', 'PM_world_info', 'rawanaltaha_world_info', 'world_info_maciej1977-v3']
['Vaishnavi_example_dataset', 'world_info_jack', 'yaswanth_world_info', 'world_info_jb', 'fjpg_world_info_jack']
['world_info_jack_1', 'world_info_jacktestfdafsdf', 'Simon_world_info', 'ole_wammer_world_info', 'LGH1']
['world_info_H', '222nd level', 'Arya_World_Info', 'teodor_world_info', 'GCH_world_info']
['tsk_world_info', 'my_example_dataset', 'irma_test', 'irma_test', 'world_info_asade']
['Shaurya_2023-ds', 'world_info_jack', 'my_example_dataset1', 'Simon_world_info', 'world_info_rui']
['world_info_jack', 'world_info_camilla2', 'gcbiotec_world_info2002A', 'world_info_SumitB', 'jeeva_world_info']
['GCH_world_info', 'my_example_dataset', 'my_test_dataset', 'camilla1996_world_info', 'PM_world_info']
['Rafli_world_info', 'clement_world_info', 'world_info_jack_lundemo', 'neil_world_info', 'DP_TestDS']
['Srujana_world_info', 'hmnasri_world_info', 'world_info_jack', 'world_info_jack', 'world_info_maxim']
['Aranya_example_dataset', 'as_dataset1', 'dls_example_dataset', 'Shirin_world_info', 'Rafli_world_info']
['Sudil1997', 'jn_example_dataset', 'cristian_example_dataset', 'sid1974', 'hmnasri-CDF']
['caroline_f_world_info2', 'Aranya_world_info', 'my_example_dataset_saketh', 'Simon_world_info', 'my_ds']
['christian_world_info', 'world_info_andrew', 'heman_2nd_dateset', 'my_world_info', 'Aqilah1993-AvevaNet']
['GCH_world_info', 'mylittlepony_world_info', 'work_info_jack', 'world_info_moe4', 'second example']
['world_info_jack_002', 'kiyoshi_world_info', 'my_example_dataset', 'my_example_dataset_k', 'second example']
['world_info_jack_test1', 'Dzmitry1994_world_info', 'victor1_example_dataset', 'Tat2_world_info', 'Alf57_world_info']
['Aidar_world_info', 'world_info_jack', 'Saurabh_world_info', 'E_world_info', 'test_dataset7']
['world_info_jack_111', 'world_info_orjanm', 'ConocoPhillips_Sensor', 'dp1998', 'world_info_anto']
['Saurabh_world_info', 'hamdi_world_info', 'my_example_dataset_sebastian1999', 'Adriano2024_example_dataset', 'AElena_world_info']
['gustavo_world_info', 'Simon_world_info', 'world_info_jack', 'world_info_Hachem', 'jeeva_testing']
['cdf_training_fjpg2', 'world_info_jack_rack', 'ownworld_info_jack', 'palvo_world_info', 'Ravi_World_info4']
['yoan_world_info', 'Jorgen_world_info', 'my_example_dataset', 'Custom Create Dataset', 'lucas_2000_example_dataset']
['Paniz_example_dataset', 'world_info_dima', 'Aidar_world_info', 'world_info_test', 'world_info_jack329']
['world_info_jack', 'demo23', 'my_example_dataset', 'pallab_example_dataset', 'Valhall OID']
['Maciukas_world_info', 'Teste_Teste_Teste', 'world_info_jack', 'world_info_jack', 'my example']
['my_example_dataset_js2001', 'Istvan_world_info', 'DipeshY_world_info', 'tsk_world_info', 'lsun_example_dataset2']
['gabor_world_info', 'leann1993_world_info_jack', 'elize_world_info', 'zhanat_world_info', 'my_example_datasetcs']
['sid1974-world_info', 'world_info', 'mikita_world_info', 'test_dataset3', 'my_example_dataset']
['srujana_world_info', 'HansGünter_example_dataset', 'my_example_dataset_ww', 'world_info_jac', 'Pavan1978-IFSDB']
['MatiasRamsland_world_info', 'third example', 'Mark303-IFSDB', 'Sean1985_world_info', 'Vipul_example_dataset']
['2nd level_test', 'emma_example_dataset', 'JP 2nd level', 'world_info_jack', 'irma_test']
['world_info_orjan', 'ds_4', 'pallab_world_info', 'PM_2nd level', 'Jorgen_world_info']
['world_info_jack_name', '1st lavel', 'felipef_example_dataset', 'world_info_john_3', 'GCH_world_info']
['world_info_maksym1981_2', 'my_example_datasetEPC', 'Him3_dataset', 'my_example_dataset', None]
['world_info_mugless', 'paco_example_dataset', 'anj_world_info', 'my_example_dataset', 'my_name2_example_dataset']
['world_info_jack_mm1', 'my_example_dataset_nick', 'Mudassir_world_info', 'toye_world_info', 'clayton_harlin_world_info']
['TestDataset', 'world_info_jack123a', 'mauricio-world-info-test2-exercise', '1st level', 'Ruslan_world_info']
['world_info_jack_name', 'TestDataset', 'Training1-AvevaNet', 'PM_world_info', 'irma_test']
['world_info_jack', 'Simon_world_info', 'my_name___example_dataset', 'world_info_xiaozhang', 'world_info_jack_mariana']

## Searching in CDF

- Search the CDF resource types
- Filter the search results

**Code Pattern**

`client.<cdf_resource_type>.search()`

### Fuzzy Search on one field

In [26]:
c.assets.search(name="Norway",limit=5)

AssetList([<cognite.client.data_classes.assets.Asset at 0x1e1f38abfd0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36d2c50>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3847350>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38ab990>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f38d72d0>])

In [28]:
c.time_series.search(name="North",limit=5)

TimeSeriesList([<cognite.client.data_classes.time_series.TimeSeries at 0x1e1f3aa3ed0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1e1f3845150>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1e1f381b050>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1e1f1d710d0>,
                <cognite.client.data_classes.time_series.TimeSeries at 0x1e1f38ea190>])

In [29]:
c.files.search(name="sheet")

FileMetadataList([<cognite.client.data_classes.files.FileMetadata at 0x1e1f38eb010>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f3ab12d0>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38eb450>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38e8f90>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38e8750>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38e9cd0>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38e9350>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38d71d0>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38d6fd0>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38ebc90>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38d7e90>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38d6e10>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38d7950>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38d7d10>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38f6550>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38f6510>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38f64d0>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38f6350>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38f6490>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38f6450>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38f6410>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38f63d0>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38f6390>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38f6310>,
                  <cognite.client.data_classes.files.FileMetadata at 0x1e1f38f65d0>])

Similarly for sequences and events

`c.sequences.search(name="some name")`

`c.events.search(description="some description")`

### Multi-field fuzzy search

In [22]:
c.assets.search(query="Nor",limit=5)

AssetList([<cognite.client.data_classes.assets.Asset at 0x1e1f36d3b90>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3a9f490>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f1773f10>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3aa05d0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3aa0ed0>])

### Exact search on one field (e.g. name, description etc)

In [23]:
c.assets.search(filter={"name": "Canada"})

AssetList([<cognite.client.data_classes.assets.Asset at 0x1e1f3827b10>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3aa35d0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3aa0b50>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3aa1610>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3aa1250>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3aa1910>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3846410>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f36f4910>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3aa3e50>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3aa3610>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3ab1e90>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3ab0dd0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3ab2e10>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3ab2c50>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3ab2d90>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3ab2d50>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3ab2d10>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3ab2cd0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3ab2c90>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3ab2c10>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3ab2ed0>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3ab2e90>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3ab2f10>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3ab2f50>,
           <cognite.client.data_classes.assets.Asset at 0x1e1f3ab2f90>])

get all timeseries for the above asset

In [ ]:
c.time_series.search(filter={"asset_ids":[8516698919785878]})

In [ ]:
c.events.list()[0].type

In [ ]:
# First get an example type to filter on
example_type = c.events.list()[0].type
# Filter the events of that type
c.events.search(filter={"type":example_type})

### Multiple filters in search function

In [ ]:
c.assets.list(limit=5,data_set_external_ids=['world_info_academy'])

In [ ]:
c.data_sets.list()

In [ ]:
c.assets.list(root=True)

In [ ]:
c.assets.search(name="San",filter={"parent_ids": [349354003007241]})

### Filter asset search using Label Filter

In [ ]:
from cognite.client.data_classes import AssetFilter

In [ ]:
c.assets.search(name="Norway",filter=AssetFilter(labels=LabelFilter(contains_all=["cold-countries"])),limit=5)

In [ ]:
c.assets.search(name="Can",filter=AssetFilter(labels=LabelFilter(contains_all=["cold-countries"])),limit=5)

## Retrieve the CDF resource types and data

### Code Pattern
`client.<cdf_resource_type>.retrieve()`

`client.<cdf_resource_type>.retrieve_multiple()`

### Retrieve the CDF resource types

single item - using id

In [ ]:
c.data_sets.list()

In [ ]:
# id of dataset
c.data_sets.retrieve(id=2238694842784134)

In [ ]:
c.time_series.retrieve(id=2238694842784134)

In [ ]:
import datetime
# id of timeseries
c.time_series.data.retrieve(id=658605450035112, start=datetime.datetime(2018,1,1), end=datetime.datetime(2018,2,1))

single item - using external_id

In [ ]:
c.data_sets.retrieve(external_id = "world_info_academy")

multiple items - using ids

In [ ]:
c.data_sets.list()

In [ ]:
c.data_sets.retrieve_multiple(ids=[39210236434027, 145208858652069])

multiple items - using external_ids

In [ ]:
c.data_sets.retrieve_multiple(external_ids=["test_dataset1", "test_dataset2","my_important_dataset"], ignore_unknown_ids=True)

In [ ]:
from datetime import datetime
# Don't put a long datetime range, as it'll fetch all the raw datapoints, which can be huge
c.time_series.data.retrieve(external_id=['Nauru_population','Spain_population'],start=datetime(2000,1,1),end=datetime(2024,1,2))

### Retrieve all items related to an asset

In [ ]:
# get the asset object for "Europa"
asset_obj = c.assets.retrieve(id = 349354003007241)

In [ ]:
asset_obj

Asset Subtree

In [ ]:
c.assets.retrieve_subtree(id = 349354003007241)

Children

In [ ]:
asset_obj.children()

Parent

In [ ]:
asset_obj.parent()

Events

In [ ]:
# get the asset object for "Italy"
asset_obj = c.assets.retrieve(id = 2689912833887590)

In [ ]:
asset_obj.events(limit=-1)

Timeseries

In [ ]:
# get the asset object for "Italy"
asset_obj = c.assets.retrieve(id = 2689912833887590)

In [ ]:
asset_obj.time_series()

### Retrieve data

#### Retrieve Raw Data

In [ ]:
# Don't put a long datetime range, as it'll fetch all the raw datapoints, which can be huge for Raw datapoints
c.time_series.data.retrieve(id=239507005016003, end='now')

#### Retrieve Aggregated data

In [ ]:
c.time_series.data.retrieve_dataframe(id=239507005016003,
                    end='1000w-ago',
                    aggregates=["average","sum"],
                    granularity="1h")

Retrieve latest datapoint before a particular time (last or any past time point)

In [ ]:
c.time_series.data.retrieve_latest(id=239507005016003, before="5w-ago")[0]

### Plot the data points

In [ ]:
c.time_series.data.retrieve(id=239507005016003, end='1000w-ago').to_pandas().plot()

### Download files

Download files to disk

In [ ]:
files_list = c.files.search(filter={"uploaded":True},limit=5)
files_list

In [ ]:
! mkdir files

In [ ]:
c.files.download(directory="files", id=[202614441188439, 4009508514690241])

Download a single file to a specific path

In [ ]:
c.files.download_to_path("files/test.svg", id=202614441188439)